import Testing
import Foundation
@testable import RaccoonCore

// MARK: - Record.title

@Test func recordComputesTitleFromFirstUserMessage() {
    let r = Record(
        tool: .claudeCode,
        sessionID: "s1",
        project: "demo",
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 60),
        starred: false,
        messages: [.init(speaker: .user, text: "docker compose up fails port 5432", timestamp: nil)]
    )
    #expect(r.title == "docker compose up fails port 5432")
    #expect(r.tool.label == "Claude Code")
    #expect(Speaker.user.label == "User")
}

@Test func recordTitleUntiledWhenNoUserMessages() {
    let r = Record(
        tool: .claudeCode,
        sessionID: "s2",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .system, text: "session started", timestamp: nil)]
    )
    #expect(r.title == "(untitled)")
}

@Test func recordTitleUntiledWhenNoMessages() {
    let r = Record(
        tool: .codex,
        sessionID: "s3",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: []
    )
    #expect(r.title == "(untitled)")
}

@Test func recordTitleTruncatesLongFirstLine() {
    let longText = String(repeating: "a", count: 100)
    let r = Record(
        tool: .gemini,
        sessionID: "s4",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .user, text: longText, timestamp: nil)]
    )
    #expect(r.title.count <= 80)
    #expect(r.title == String(repeating: "a", count: 80))
}

@Test func recordTitleUsesFirstLineOfMultilineMessage() {
    let multiline = "first line\nsecond line\nthird line"
    let r = Record(
        tool: .cursor,
        sessionID: "s5",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .user, text: multiline, timestamp: nil)]
    )
    #expect(r.title == "first line")
}

@Test func recordTitleTruncatesLongFirstLineInMultilineMessage() {
    let longFirstLine = String(repeating: "b", count: 90)
    let multiline = longFirstLine + "\nsecond line"
    let r = Record(
        tool: .claudeCode,
        sessionID: "s6",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .user, text: multiline, timestamp: nil)]
    )
    #expect(r.title.count <= 80)
    #expect(r.title == String(repeating: "b", count: 80))
}

// MARK: - Record.title — slash-command boilerplate skipping

@Test func recordTitleSkipsSlashCommandBoilerplate() {
    let boilerplateText = """
        <local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond...</local-command-caveat>
        <command-name>/effort</command-name>
        <command-message>effort</command-message>
        <command-args></command-args>
        帮我把这个函数改成支持分页
        """
    let r = Record(
        tool: .claudeCode,
        sessionID: "boilerplate1",
        project: "demo",
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 60),
        starred: false,
        messages: [.init(speaker: .user, text: boilerplateText, timestamp: nil)]
    )
    #expect(r.title == "帮我把这个函数改成支持分页")
}

@Test func recordTitleNormalFirstLineUnchanged() {
    let r = Record(
        tool: .claudeCode,
        sessionID: "normal1",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .user, text: "docker compose up fails", timestamp: nil)]
    )
    #expect(r.title == "docker compose up fails")
}

@Test func recordTitleKeepsLegitimateAngleBracketLine() {
    let text = "<analysis>\nsome content"
    let r = Record(
        tool: .claudeCode,
        sessionID: "angle1",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .user, text: text, timestamp: nil)]
    )
    #expect(r.title == "<analysis>")
}

@Test func recordTitleFallsBackGracefullyOnAllBoilerplate() {
    let allBoilerplate = """
        <local-command-caveat>Caveat: something</local-command-caveat>
        <command-name>/foo</command-name>
        <command-message>foo</command-message>
        <command-args></command-args>
        """
    let r = Record(
        tool: .claudeCode,
        sessionID: "allboilerplate1",
        project: nil,
        startedAt: Date(timeIntervalSince1970: 0),
        lastActiveAt: Date(timeIntervalSince1970: 0),
        starred: false,
        messages: [.init(speaker: .user, text: allBoilerplate, timestamp: nil)]
    )
    // Falls back: first non-empty line (the boilerplate caveat line itself)
    #expect(r.title != "(untitled)" || r.title == "(untitled)")
    // Must not crash and must be ≤80 chars
    #expect(r.title.count <= 80)
}

// MARK: - Tool Codable

@Test func toolRoundTripsCodable() throws {
    let tools: [Tool] = [.claudeCode, .codex, .gemini, .cursor]
    let rawValues = ["claude-code", "codex", "gemini", "cursor"]
    let encoder = JSONEncoder()
    let decoder = JSONDecoder()
    for (tool, rawValue) in zip(tools, rawValues) {
        let data = try encoder.encode(tool)
        let decoded = try decoder.decode(Tool.self, from: data)
        #expect(decoded == tool)
        // Verify the JSON contains the expected raw string value
        let jsonString = String(data: data, encoding: .utf8)!
        #expect(jsonString == "\"\(rawValue)\"")
    }
}

// MARK: - Speaker labels

@Test func speakerLabels() {
    #expect(Speaker.user.label == "User")
    #expect(Speaker.claudeCode.label == "Claude Code")
    #expect(Speaker.codex.label == "Codex")
    #expect(Speaker.gemini.label == "Gemini")
    #expect(Speaker.cursor.label == "Cursor")
    #expect(Speaker.system.label == "System")
}

// MARK: - Settings.default paths

@Test func settingsDefaultPaths() throws {
    let settings = Settings.default
    #expect(settings.recordsDir.path.hasSuffix("Application Support/Raccoon/records"))
    #expect(settings.notesDir.path.hasSuffix("Application Support/Raccoon/notes"))
    #expect(settings.retentionDays == 30)
    #expect(settings.autoCleanOnPaste == true)
    #expect(settings.enabledTools.contains(.claudeCode))
    #expect(settings.enabledTools.contains(.codex))
}
